trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'testimage'
  dockerRegistry: 'containerregistrysaidpk.azurecr.io' # Replace with your ACR URL
  dockerfilePath: './dockerfile' # Update this path if your Dockerfile is in a different location

stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: BuildJob
    displayName: 'Build Docker Image Job'
    steps:
    - script: echo Building Docker image
      displayName: 'Step 1: Build Docker Image'
      
    - task: Docker@2
      displayName: 'Step 2: Build Docker Image'
      inputs:
        command: 'build'
        arguments: '-t $(dockerRegistry)/$(imageName):$(Build.BuildId) -f $(dockerfilePath) .'
      
- stage: Push
  displayName: 'Push Docker Image'
  jobs:
  - job: PushJob
    displayName: 'Push Docker Image Job'
    steps:
    - task: Docker@2
      displayName: 'Step 1: Push Docker Image'
      inputs:
        command: 'push'
        containerRegistry: 'testacrsaidpk' # Replace with the name of your Azure Container Registry service connection
        repository: '$(dockerRegistry)/$(imageName):$(Build.BuildId)'
        tags: |
          latest
